queue_rules:
  - name: default
    autoqueue: true
    merge_method: rebase
    update_method: rebase
    queue_conditions:
      - check-success = "check-macos-linux-nix"
      - check-success = "check-macos-linux-nix-private"
      - check-success = "pre-commit.ci - pr"
      - or:
          - approved-reviews-by = arntanguy
          - author = dependabot[bot]
          - author = mc-rtc-nixpkgs-flake-updater[bot]
          - author = github-actions[bot]
          - author = pre-commit-ci[bot]
