name: "CI - Nix - Private"
on:
  push:
    branches:
      - main
      - private-attic
  pull_request:
    branches:
      - main
jobs:
  populate-cache:
    name: "${{ matrix.build }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        # test with mc-hrp2 for now
        build: ["mc-hrp2"]
    steps:
      - uses: actions/checkout@v6
      # Configures ssh-agent if SSH_KEY secret exists
      - name: Configure ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: cachix/install-nix-action@v31
      # read-only cache
      - uses: cachix/cachix-action@v17
        with:
          name: mc-rtc-nix
          extraPullNames: "ros,gepetto"
      # will push all paths not already in the public cache
      - name: Setup Attic cache (private)
        uses: ryanccn/attic-action@v0
        with:
          endpoint: https://attic.arntanguy.fr
          cache: mc-rtc-nix-private
          token: ${{ secrets.ATTIC_TOKEN }}
      - run: nix build -L "./private#${{ matrix.build }}" --cores 4
  complete:
    needs: populate-cache
    name: "complete ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu] # TODO: macos
    steps:
      - uses: jlumbroso/free-disk-space@main
        if: ${{ matrix.os == 'ubuntu' }}
      - name: Configure ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: mc-rtc-nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: "ros,gepetto"
      - run: nix flake check -L ./private
  fallback:
    needs: complete
    if: always() && needs.complete.result == 'failure'
    name: "fallback ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu] # TODO: macos
    steps:
      - uses: jlumbroso/free-disk-space@main
        if: ${{ matrix.os == 'ubuntu' }}
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: mc-rtc-nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: "ros,gepetto"
      - run: nix flake check -L -j 1 --cores 1
  # system:
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: cachix/install-nix-action@v31
  #     - uses: cachix/cachix-action@v17
  #       with:
  #         name: mc-rtc-nix
  #         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
  #         extraPullNames: ros
  #     - run: nix build -L .#systemConfigs.default
  # home:
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: cachix/install-nix-action@v31
  #     - uses: cachix/cachix-action@v17
  #       with:
  #         name: mc-rtc-nix
  #         extraPullNames: "ros,gepetto"
  #     - run: nix build -L .#homeConfigurations.cpene.activationPackage
  check:
    if: always()
    name: check-macos-linux-nix-private
    runs-on: ubuntu-latest.mer
    needs:
      - fallback
      # - system
      # - home
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: fallback
          jobs: ${{ toJSON(needs) }}

