name: "CI - Nix - Variants Private"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  populate-cache:
    # - This condition allows the job to run if:
    #   - The workflow is not triggered by a pull request (`github.event_name != 'pull_request'`), or
    #   - The PR's source repo is the same as the base repo.
    # This is done to make sure that the required secrets are available to the CI
    if: github.event_name != 'pull_request' || github.repository == github.event.pull_request.head.repo.full_name
    name: "${{ matrix.build }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        # test with mc-hrp2 for now
        build: [ "mc-rtc-superbuild-private" ]
    steps:
      - uses: actions/checkout@v6
      # Configures ssh-agent if SSH_KEY secret exists
      - name: Configure ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add gite.lirmm.fr to known_hosts
        run: |
          ssh-keyscan gite.lirmm.fr >> ~/.ssh/known_hosts
      - uses: cachix/install-nix-action@v31
      # read-only cache
      - uses: cachix/cachix-action@v17
        with:
          name: mc-rtc-nix
          extraPullNames: "ros,gepetto"
      # will push all paths not already in the public cache
      - name: Setup Attic cache (private)
        uses: ryanccn/attic-action@v0
        with:
          endpoint: https://attic.arntanguy.fr
          cache: mc-rtc-nix-private
          token: ${{ secrets.ATTIC_TOKEN }}
      - run: nix build -L ".#variants.private.packages.x86_64-linux.${{ matrix.build }}" --cores 4
  fallback:
    needs: populate-cache
    if: always() && needs.populate-cache.result == 'failure'
    name: "fallback ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu] # TODO: macos
    steps:
      - uses: jlumbroso/free-disk-space@main
        if: ${{ matrix.os == 'ubuntu' }}
      - name: Configure ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add gite.lirmm.fr to known_hosts
        run: |
          ssh-keyscan gite.lirmm.fr >> ~/.ssh/known_hosts
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: mc-rtc-nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: "ros,gepetto"
      - run: nix build -L ".#variants.private.packages.x86_64-linux.${{ matrix.build }}" --cores 4
  check:
    if: always()
    name: check-macos-linux-nix-private
    runs-on: ubuntu-latest
    needs:
      - fallback
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: fallback
          jobs: ${{ toJSON(needs) }}

